### ISSUE TITLE
props returning null

### ISSUE THREAD

**Issue by gcosgreave-us** [substate/react-priority-nav#1]
Is this currently still being supported? I would really like to use it, but currently I am getting the following error

<img width="670" alt="screen shot 2019-01-09 at 18 01 23" src="https://user-images.githubusercontent.com/39494540/50918616-a5915500-1438-11e9-8224-0c254c5a497f.png">

**Comment by gcosgreave-us** [comment]
Any traction on this?

**Comment by decimoseptimo** [comment]
This project seems dead, use the [original script](https://github.com/gijsroge/priority-navigation) as legacy code.

**Comment by gcosgreave-us** [comment]
Its cool, we pretty much did that now anyway
